name: CI + CD

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    name: Lint & Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Set up Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: "3.12"
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install ruff pytest
#          pip install -r requirements.txt

      - name: Ruff check
        uses: astral-sh/ruff-action@v3

#      - name: Run tests
#        run: |
#          pytest

#  deploy:
#    name: Deploy to VDS
#    runs-on: ubuntu-latest
#    needs: test
#    if: success()
#
#    steps:
#      - name: Deploy via SSH
#        uses: appleboy/ssh-action@v1.0.0
#        with:
#          host: ${{ secrets.VDS_HOST }}
#          username: ${{ secrets.VDS_USER }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          script: |
#            cd ${{ secrets.VDS_PATH }}
#            git pull
#            docker compose down
#            docker compose up -d --build
